name: Test and Deploy

# Run this workflow only when a tag is pushed
# Can set custom wildcards instead of '*', like 'v*' for tags starting with v
# NOTE: Releases are only published on tags, see "Release" step below
on:
  push:
    tags:
      - '*'

# Docs on sharing data between jobs (between VMs): https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#passing-data-between-jobs-in-a-workflow
jobs:
  # Linux/Mac Build
  linux_mac_build:
    name: Deploy Umineko Question Scripts
    runs-on: ubuntu-latest
    steps:
      # Download the 'master' script repo (contains full and voice-only scripts)
      - uses: actions/checkout@v2
        with:
          ref: master
          path: master

      # Download the 'adv_mode' script repo (contains only adv-mode script)
      - uses: actions/checkout@v2
        with:
          ref: adv_mode
          path: adv_mode

      # Run Deploy Script
      - name: Run Deploy Script
        run: |
          echo ${{ github.ref }} >> 0.u.version.txt
          date >> 0.u.version.txt
          mv ./master/0.utf ./master/0.u
          7z a script-full.7z ./master/0.u 0.u.version.txt
          mv ./master/voices-only/0.utf ./master/voices-only/0.u
          7z a script-voice-only.7z ./master/voices-only/0.u 0.u.version.txt
          mv ./adv_mode/0.utf ./adv_mode/0.u
          7z a script-adv-mode.7z ./adv_mode/0.u 0.u.version.txt

      # Publish a release
      # For more info on options see: https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # only publish tagged commits
        with:
          files: |
            script-full.7z
            script-voice-only.7z
            script-adv-mode.7z
          body_path: ./master/github_actions_changelog_template.txt
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
